# Generated by Django 3.2.7 on 2021-10-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('api_id', models.UUIDField(primary_key=True, serialize=False)),
                ('game', models.TextField(verbose_name='name')),
                ('device', models.TextField(verbose_name='device')),
                ('player', models.TextField(verbose_name='player nick')),
                ('player_twitch', models.TextField(blank=True, verbose_name='twitch')),
                ('published', models.TextField(blank=True, verbose_name='publishing year')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True)),
                ('vod_link', models.URLField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('estimate', models.PositiveIntegerField(verbose_name='estimate in seconds')),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='vj_cms_timetable', serialize=False, to='cms.cmsplugin')),
                ('hide_past', models.BooleanField()),
                ('show_vods', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
