# Generated by Django 3.2.8 on 2021-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='img_filename',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='estimate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='estimate in seconds'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='game',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='player',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='player nick'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='player_twitch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='twitch'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='published',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='publishing year'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='vod_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
