# Generated by Django 3.2.12 on 2022-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_cms', '0003_auto_20211102_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='meta',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
