# Generated by Django 3.2.18 on 2023-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_cms', '0004_gameinfo_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('api_id', models.UUIDField(primary_key=True, serialize=False)),
                ('discord_nick', models.CharField(default='', max_length=255, null=True)),
                ('display_name', models.CharField(default='', max_length=255, null=True)),
                ('twitch_channel', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
