# Generated by Django 3.2.18 on 2023-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_cms', '0005_playerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='players',
            field=models.ManyToManyField(related_name='games', to='vj_cms.PlayerInfo'),
        ),
    ]
