# Generated by Django 3.2.23 on 2024-11-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('vj_cms', '0006_gameinfo_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='vj_cms_anchorlink', serialize=False, to='cms.cmsplugin')),
                ('anchor_tag', models.CharField(default='', max_length=255, null=True, verbose_name='Anchor tag')),
                ('title', models.CharField(default='', max_length=255, null=True, verbose_name='Title in menu (Empty = hidden)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PriorityMessages',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='vj_cms_prioritymessages', serialize=False, to='cms.cmsplugin')),
                ('duration', models.PositiveIntegerField(default=8, verbose_name='Carousel message duration (seconds)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
