# Generated by Django 3.2.25 on 2024-11-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('vj_cms', '0007_anchorlink_prioritymessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweakSettings',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='vj_cms_tweaksettings', serialize=False, to='cms.cmsplugin')),
                ('message_duration', models.PositiveIntegerField(default=8, verbose_name='Carousel message duration (seconds)')),
                ('show_scrolldown_menu', models.BooleanField(default=False, verbose_name='Show scrolldown menu')),
                ('show_login', models.BooleanField(default=True, verbose_name='Show login')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
