# Generated by Django 3.2.25 on 2025-03-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('vj_cms', '0008_tweaksettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityMessages',
        ),
    ]
