# Generated by Django 3.2.25 on 2025-04-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('vj_cms', '0009_delete_prioritymessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorLogoHolder',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='vj_cms_sponsorlogoholder', serialize=False, to='cms.cmsplugin')),
                ('size', models.CharField(default='M', max_length=1, verbose_name='Logo size (L/M/S)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
