version: '3'

services:
  web:
    container_name: vj-cms
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: vauhtijuoksu.settings.docker
    entrypoint: /home/cms/scripts/docker_entrypoint.sh
    volumes:
      - ./marathon:/home/cms/marathon
      - ./vauhtijuoksu:/home/cms/vauhtijuoksu
      - ./templates:/home/cms/templates
      - ./static:/home/cms/static
      - ./sassfiles:/home/cms/sassfiles
      - cms-media:/home/cms/media
    ports:
      - 8000:8000

  db:
    container_name: vj-cms-db
    image: postgres:11
    environment:
      POSTGRES_USER: vjcms
      POSTGRES_PASSWORD: vjcmsPasswd
      POSTGRES_DB: vjcms
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  cms-media:
