# Generated by Django 3.2.12 on 2022-03-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0003_auto_20220207_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='gdpr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='for_children',
            field=models.BooleanField(default=False, help_text='Runin sisältö ja selostus ovat lapsiyleisölle sopivia', verbose_name='sopiva lapsille'),
        ),
    ]
