# Generated by Django 3.2.13 on 2023-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0005_event_gdpr_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gmail',
            field=models.EmailField(blank=True, help_text='Mieluiten Gmail-osoite jota käytetään tiedotukseen sekä\n        tapahtumaan liittyvien tiedostojen, kuten aikataulun jakamiseen', max_length=254, null=True, verbose_name='sähköpostiosoite'),
        ),
    ]
