# Generated by Django 3.2.13 on 2023-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0005_event_gdpr_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gmail',
            field=models.EmailField(help_text='Mieluiten Gmail-osoite jota käytetään tiedotukseen sekä\n        tapahtumaan liittyvien tiedostojen, kuten aikataulun jakamiseen', max_length=254, null=True, verbose_name='sähköpostiosoite'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='console_display',
            field=models.CharField(blank=True, max_length=29, null=True, verbose_name='emuloitava laite/konsoli'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='estimate',
            field=models.CharField(help_text='Arvioi runin kestolle yläraja (tunnit:minuutit) alusta loppuun viiden minuutin tarkkuudella.', max_length=20, verbose_name='aika-arvio'),
        ),
    ]
