# Generated by Django 3.2.13 on 2023-01-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0006_player_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='estimate',
            field=models.CharField(help_text='Arvioi runin kestolle yläraja (tunnit:minuutit) alusta loppuun viiden minuutin tarkkuudella.', max_length=20, verbose_name='aika-arvio'),
        ),
    ]
