# Generated by Django 3.2.18 on 2024-01-18 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0006_submission_updates_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='priority',
            field=models.IntegerField(default=1, help_text='jos ehdotat useampaa peliä (1=mieluisin)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='tärkeysjärjestys'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='console',
            field=models.CharField(max_length=29, verbose_name='laite/konsoli, jolla pelaat'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='estimate',
            field=models.CharField(help_text='Arvioi suorituksen kestolle yläraja (tunnit:minuutit) alusta loppuun. Ota arviossa huomioon terveisten lähettämiset ja mahdolliset virheet runissa.', max_length=20, verbose_name='aika-arvio'),
        ),
    ]
