# Generated by Django 3.2.23 on 2025-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0008_alter_submission_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='personal_best',
            field=models.CharField(max_length=20, null=True, verbose_name='Tämänhetkinen henkilökohtainen ennätyksesi'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, verbose_name='miksi tämä runi?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='estimate',
            field=models.CharField(help_text='Arviosi suorituksen kestosta. Ota arviossa huomioon terveisten lähettämiset ja mahdolliset virheet runissa.', max_length=20, verbose_name='aika-arvio'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gdpr',
            field=models.BooleanField(default=False, verbose_name='Hyväksyn henkilötietojeni käsittelyn %%tietosuojaselosteen%% mukaisesti.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_constraints',
            field=models.TextField(blank=True, help_text='Mikäli sinulle kelpaavat ajat muuttuvat, voit korjata tiedot ilmoittautumisen päätyttyä.', verbose_name='aikataulurajoitteet'),
        ),
    ]
