# Generated by Django 3.2.23 on 2025-02-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0008_alter_submission_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(verbose_name='alkaen')),
                ('window_end', models.DateTimeField(verbose_name='päättyen')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.submission')),
            ],
        ),
    ]
