# Generated by Django 3.2.23 on 2026-02-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0009_auto_20250907_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gdpr_notice_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tietosuojaseloste linkkinä'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gdpr_notice',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Tietosuojaseloste tiedostona'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_constraints',
            field=models.TextField(blank=True, default='', help_text='Mikäli sinulle kelpaavat ajat muuttuvat, voit korjata tiedot myöhemmin.', verbose_name='aikataulurajoitteet'),
        ),
    ]
