apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/django-env.yaml") . | sha256sum }}
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: cms
        image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        args:
        - gunicorn
        - vauhtijuoksu.wsgi:application
        - --bind
        - 0.0.0.0:8000
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - mountPath: {{ .Values.django.static_root }}
          name: django-static
        - mountPath: {{ .Values.django.sass_root }}
          name: django-scss
        - mountPath: {{ .Values.django.media_root }}
          name: django-media
        envFrom:
        - configMapRef:
            name: django-env
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secret }}
              key: password
              optional: false
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.django.secret }}
              key: secret
              optional: false
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.storage.secret }}
              key: key
              optional: true
      volumes:
      - name: django-static
        emptyDir: {}
      - name: django-scss
        emptyDir: {}
      # TODO: Persistent media volume
      - name: django-media
        emptyDir: {}
