apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        {{- range .Values.http.hosts }}
        - {{ . }}
        {{- end }}
      secretName: cms-tls
  ingressClassName: traefik
  rules:
    {{- $svc := .Chart.Name }}
    {{- range $host := .Values.http.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $svc }}
                port:
                  name: http
            path: /
            pathType: Prefix
    {{- end }}
