apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    # To work on kind cluster
    nginx.ingress.kubernetes.io/server-alias: localhost
spec:
  tls:
    - hosts:
        - {{ .Values.http.host }}
        - www.vauhtijuoksu.fi
        - vauhtijuoksu.fi
  ingressClassName: traefik
  rules:
    - host: {{ .Values.http.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: www.vauhtijuoksu.fi
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: vauhtijuoksu.fi
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  name: http
            path: /
            pathType: Prefix
