---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vjcms.fullname" . }}
  labels:
    {{- include "vjcms.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vjcms.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: {{ .Values.gunicorn.listenPort }}
