database:
  address: postgres-rw.postgres.svc.cluster.local
  database: wwwauhtijuoksu-cms
  secret: vjcms-psql
  user: wwwauhtijuoksu-cms
django:
  allowed_hosts: cms.dev.vauhtijuoksu.fi,www.vauhtijuoksu.fi,vauhtijuoksu.fi
  media_url: https://vjcms.blob.core.windows.net/media/
  static_url: https://cms-static.dev.vauhtijuoksu.fi/static/
  vj_api_url: http://vauhtijuoksu-api.vauhtijuoksu-api.svc.cluster.local:8080
http:
  staticfiles_host: cms-static.dev.vauhtijuoksu.fi
image:
  registry: ghcr.io/
  repository: vauhtijuoksu/wwwauhtijuoksu-cms
