image:
  registry: ghcr.io/
  repository: vauhtijuoksu/wwwauhtijuoksu-cms
  tag: "latest"
  pullPolicy: Always

http:
  hosts:
    - www.vauhtijuoksu.fi
    - vauhtijuoksu.fi
  staticfiles_host: cms-static.vauhtijuoksu.fi

django:
  settings_module: vauhtijuoksu.settings.production
  log_level: INFO
  secret: django
  sass_root: /home/cms/sassfiles
  static_root: /home/cms/staticfiles
  static_url: https://cms-static.vauhtijuoksu.fi/static/
  media_root: /home/cms/media
  media_url: https://media.vauhtijuoksu.fi/
  vj_api_url: http://vauhtijuoksu-api.vauhtijuoksu-api.svc.cluster.local:8080

storage:
  backend: upcloud
  # Secret keys for S3 compatible storage:
  # - AWS_ACCESS_KEY_ID
  # - AWS_S3_CUSTOM_DOMAIN
  # - AWS_S3_ENDPOINT_URL
  # - AWS_S3_REGION_NAME
  # - AWS_SECRET_ACCESS_KEY
  # - AWS_STORAGE_BUCKET_NAME
  secret: cms-media-s3

database:
  address: postgres-rw.postgres.svc.cluster.local
  port: 5432
  database: wwwauhtijuoksu-cms
  # Create a secret: `kubectl create secret generic vjcms-psql --from-literal=password=myPwassrod!`
  secret: vjcms-psql
  user: wwwauhtijuoksu-cms
