image:
  registry: vauhtijuoksu.azurecr.io/
  repository: vauhtijuoksu/cms
  tag: "latest"
  pullPolicy: Always

ingress:
  enabled: true
  class: nginx
  serverAlias: localhost
  tls:
    enabled: true
    certIssuer: letsencrypt-prod
  hosts:
  - cms.dev.vauhtijuoksu.fi
  - vjcms-kubedev.azureedge.net

django:
  settings_module: vauhtijuoksu.settings.production
  allowed_hosts:
  - localhost
  - vjcms
  - cms.dev.vauhtijuoksu.fi
  - vjcms-kubedev.azureedge.net
  log_level: INFO
  secret: django
  sass_root: /home/cms/sassfiles
  static_root: /home/cms/staticfiles
  static_url: https://vjcms-kubedev.azureedge.net/static/
  media_root: /home/cms/media
  media_url: https://vjcms-media.azureedge.net/media/
  vj_api_url: https://api.dev.vauhtijuoksu.fi

gunicorn:
  application: vauhtijuoksu.wsgi:application
  workers: 3
  listenPort: 8080

storage:
  backend: azure
  account_name: vjcms
  container: media
  secret: vjcms-storage

database:
  address: vauhtijuoksu-db.postgres.database.azure.com
  port: 5432
  database: vjcms_staging
  # Create a secret: `kubectl create secret generic vjcms-psql --from-literal=password=myPwassrod!`
  secret: vjcms-psql
  user: vjcms_staging@vauhtijuoksu-db
