name: docker

on:
  push:
    branches:
    - develop
    - trunk
    tags:
    - 'v*'
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          load: true
          tags: vauhtijuoksu/cms:test

      - name: Extract Docker metadata
        if: github.event_name == 'push'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            name=${{ secrets.ACR_ENDPOINT}}/vauhtijuoksu/cms
          tags: |
            # sha for branch triggers
            type=ref,event=branch
            type=ref,event=branch,suffix=-{{sha}}
            type=ref,event=pr,suffix=-{{sha}}
            # semver only for version tags
            type=semver,pattern={{version}}

      - name: Log in to ACR
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # This should use cached image and not actually trigger a new build
      - name: Build and push images
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


        



